In [1]:
pip install pandas yfinance datasets spacy tqdm opendatasets transformers torch

Collecting pandas
  Using cached pandas-3.0.2-cp311-cp311-win_amd64.whl (9.9 MB)
Collecting yfinance
  Using cached yfinance-1.2.0-py2.py3-none-any.whl (130 kB)
Collecting datasets
  Using cached datasets-4.8.4-py3-none-any.whl (526 kB)
Collecting spacy
  Using cached spacy-3.8.14-cp311-cp311-win_amd64.whl (15.4 MB)
Requirement already satisfied: tqdm in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (4.67.3)
Collecting opendatasets
  Using cached opendatasets-0.1.22-py3-none-any.whl (15 kB)
Collecting transformers
  Using cached transformers-5.4.0-py3-none-any.whl (10.1 MB)
Collecting torch
  Using cached torch-2.11.0-cp311-cp311-win_amd64.whl (114.5 MB)
Collecting numpy>=1.26.0
  Using cached numpy-2.4.4-cp311-cp311-win_amd64.whl (12.6 MB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\calmen\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.3)
Collecting requests>=2.31
  Using cached requests-2.33.1-py3-none-any.whl (64 kB)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\calmen\appdata\roaming\python\python311\site-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (2026.1.post1)
Collecting frozendict>=2.3.4
  Using cached frozendict-2.4.7-py3-none-any.whl (16 kB)
Requirement already satisfied: peewee>=3.16.2 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (4.0.3)
Collecting beautifulsoup4>=4.11.1
  Using cached beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Collecting curl_cffi<0.14,>=0.7
  Using cached curl_cffi-0.13.0-cp39-abi3-win_amd64.whl (1.6 MB)
Collecting protobuf>=3.19.0
  Using cached protobuf-7.34.1-cp310-abi3-win_amd64.whl (437 kB)
Requirement already satisfied: websockets>=13.0 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (16.0)
Collecting filelock
  Using cached filelock-3.25.2-py3-none-any.whl (26 kB)
Collecting pyarrow>=21.0.0
  Using cached pyarrow-23.0.1-cp311-cp311-win_amd64.whl (27.5 MB)
Collecting dill<0.4.2,>=0.3.0
  Using cached dill-0.4.1-py3-none-any.whl (120 kB)
Collecting httpx<1.0.0
  Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Requirement already satisfied: xxhash in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from datasets) (3.6.0)
Collecting multiprocess<0.70.20
  Using cached multiprocess-0.70.19-py311-none-any.whl (144 kB)
Collecting fsspec[http]<=2026.2.0,>=2023.1.0
  Using cached fsspec-2026.2.0-py3-none-any.whl (202 kB)
Collecting huggingface-hub<2.0,>=0.25.0
  Using cached huggingface_hub-1.8.0-py3-none-any.whl (625 kB)
Requirement already satisfied: packaging in c:\users\calmen\appdata\roaming\python\python311\site-packages (from datasets) (25.0)
Collecting pyyaml>=5.1
  Using cached pyyaml-6.0.3-cp311-cp311-win_amd64.whl (158 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0
  Using cached spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Collecting murmurhash<1.1.0,>=0.28.0
  Using cached murmurhash-1.0.15-cp311-cp311-win_amd64.whl (25 kB)
Collecting cymem<2.1.0,>=2.0.2
  Using cached cymem-2.0.13-cp311-cp311-win_amd64.whl (40 kB)
Collecting preshed<3.1.0,>=3.0.2
  Using cached preshed-3.0.13-cp311-cp311-win_amd64.whl (122 kB)
Collecting thinc<8.4.0,>=8.3.12
  Using cached thinc-8.3.13-cp311-cp311-win_amd64.whl (1.8 MB)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from spacy) (1.1.3)
Collecting srsly<3.0.0,>=2.5.3
  Using cached srsly-2.5.3-cp311-cp311-win_amd64.whl (651 kB)
Collecting catalogue<2.1.0,>=2.0.6
  Using cached catalogue-2.0.10-py3-none-any.whl (17 kB)
Collecting weasel<2.0.0,>=1.0.0
  Using cached weasel-1.0.0-py3-none-any.whl (50 kB)
Collecting confection<2.0.0,>=1.3.2
  Using cached confection-1.3.3-py3-none-any.whl (35 kB)
Collecting typer<1.0.0,>=0.3.0
  Using cached typer-0.24.1-py3-none-any.whl (56 kB)
Collecting pydantic<3.0.0,>=2.0.0
  Using cached pydantic-2.12.5-py3-none-any.whl (463 kB)
Collecting jinja2
  Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Requirement already satisfied: setuptools in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from spacy) (65.5.0)
Requirement already satisfied: colorama in c:\users\calmen\appdata\roaming\python\python311\site-packages (from tqdm) (0.4.6)
Collecting kaggle
  Using cached kaggle-2.0.0-py3-none-any.whl (75 kB)
Collecting click
  Using cached click-8.3.1-py3-none-any.whl (108 kB)
Collecting regex>=2025.10.22
  Using cached regex-2026.3.32-cp311-cp311-win_amd64.whl (278 kB)
Collecting tokenizers<=0.23.0,>=0.22.0
  Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
Collecting safetensors>=0.4.3
  Using cached safetensors-0.7.0-cp38-abi3-win_amd64.whl (341 kB)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\calmen\appdata\roaming\python\python311\site-packages (from torch) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from torch) (1.14.0)
Collecting networkx>=2.5.1
  Using cached networkx-3.6.1-py3-none-any.whl (2.1 MB)
Collecting fsspec>=0.8.5
  Using cached fsspec-2026.3.0-py3-none-any.whl (202 kB)
Collecting soupsieve>=1.6.1
  Using cached soupsieve-2.8.3-py3-none-any.whl (37 kB)
Collecting cffi>=1.12.0
  Using cached cffi-2.0.0-cp311-cp311-win_amd64.whl (182 kB)
Collecting certifi>=2024.2.2
  Using cached certifi-2026.2.25-py3-none-any.whl (153 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1
  Using cached aiohttp-3.13.5-cp311-cp311-win_amd64.whl (462 kB)
Collecting anyio
  Using cached anyio-4.13.0-py3-none-any.whl (114 kB)
Collecting httpcore==1.*
  Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Collecting idna
  Using cached idna-3.11-py3-none-any.whl (71 kB)
Collecting h11>=0.16
  Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Collecting hf-xet<2.0.0,>=1.4.2
  Using cached hf_xet-1.4.3-cp37-abi3-win_amd64.whl (3.7 MB)
Collecting annotated-types>=0.6.0
  Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Collecting pydantic-core==2.41.5
  Using cached pydantic_core-2.41.5-cp311-cp311-win_amd64.whl (2.0 MB)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: six>=1.5 in c:\users\calmen\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting charset_normalizer<4,>=2
  Using cached charset_normalizer-3.4.6-cp311-cp311-win_amd64.whl (153 kB)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.31->yfinance) (2.6.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Collecting blis<1.4.0,>=1.3.0
  Using cached blis-1.3.3-cp311-cp311-win_amd64.whl (6.2 MB)
Collecting shellingham>=1.3.0
  Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Collecting rich>=12.3.0
  Using cached rich-14.3.3-py3-none-any.whl (310 kB)
Collecting annotated-doc>=0.0.2
  Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Collecting cloudpathlib>=0.7.0
  Using cached cloudpathlib-0.23.0-py3-none-any.whl (62 kB)
Collecting smart-open>=5.2.1
  Using cached smart_open-7.5.1-py3-none-any.whl (64 kB)
Collecting MarkupSafe>=2.0
  Using cached markupsafe-3.0.3-cp311-cp311-win_amd64.whl (15 kB)
Collecting bleach
  Using cached bleach-6.3.0-py3-none-any.whl (164 kB)
Collecting kagglesdk<1.0,>=0.1.15
  Using cached kagglesdk-0.1.16-py3-none-any.whl (160 kB)
Collecting python-slugify
  Using cached python_slugify-8.0.4-py2.py3-none-any.whl (10 kB)
Collecting aiohappyeyeballs>=2.5.0
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Collecting aiosignal>=1.4.0
  Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Collecting attrs>=17.3.0
  Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.8.0-cp311-cp311-win_amd64.whl (44 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.7.1-cp311-cp311-win_amd64.whl (45 kB)
Collecting propcache>=0.2.0
  Using cached propcache-0.4.1-cp311-cp311-win_amd64.whl (41 kB)
Collecting yarl<2.0,>=1.17.0
  Using cached yarl-1.23.0-cp311-cp311-win_amd64.whl (87 kB)
Collecting pycparser
  Using cached pycparser-3.0-py3-none-any.whl (48 kB)
Collecting markdown-it-py>=2.2.0
  Using cached markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\calmen\appdata\roaming\python\python311\site-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: wrapt in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.1.2)
Requirement already satisfied: webencodings in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from python-slugify->kaggle->opendatasets) (1.3)
Collecting mdurl~=0.1
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: spacy-loggers, spacy-legacy, soupsieve, smart-open, shellingham, safetensors, regex, pyyaml, python-slugify, pydantic-core, pycparser, pyarrow, protobuf, propcache, numpy, networkx, murmurhash, multidict, mdurl, MarkupSafe, idna, hf-xet, h11, fsspec, frozenlist, frozendict, filelock, dill, cymem, confection, cloudpathlib, click, charset_normalizer, certifi, catalogue, bleach, attrs, annotated-types, annotated-doc, aiohappyeyeballs, yarl, srsly, requests, pydantic, preshed, pandas, multiprocess, markdown-it-py, jinja2, httpcore, cffi, blis, beautifulsoup4, anyio, aiosignal, torch, thinc, rich, kagglesdk, httpx, curl_cffi, aiohttp, yfinance, typer, kaggle, weasel, opendatasets, huggingface-hub, tokenizers, spacy, datasets, transformers
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script slugify.exe is installed in 'c:\Users\Calmen\AppData\Local\Programs\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\Users\\Calmen\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\lib\\tests\\test_io.py'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip available: 22.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
!python -m spacy download en_core_web_md

c:\Users\Calmen\AppData\Local\Programs\Python\Python311\python.exe: No module named spacy

MasterData Building

In [ ]:
import os
import requests
import pandas as pd
import time
from datetime import datetime
from calendar import monthrange
from dotenv import load_dotenv
import os

load_dotenv()

API_KEY = os.getenv("ALPHAVANTAGE_API_KEY")
BASE_URL = "https://www.alphavantage.co/query"

MY_TICKERS = {
    'CL=F', 'USO', 'XOM', 'CVX', 'BP', 'SHEL', 'COP', 'EOG', 'OXY', 'XLE', 'XOP',
    'HO=F', 'CRAK', 'VLO', 'MPC', 'PSX', 'NG=F', 'UNG', 'LNG', 'TELL', 'EQT', 'RRC'
}

def harvest_chunk(year: int, month: int) -> list:
    """Fetch up to 1000 articles for one month."""
    last_day = monthrange(year, month)[1]
    time_from = f"{year}{month:02d}01T0000"
    time_to = f"{year}{month:02d}{last_day:02d}T2359"

    params = {
        "function": "NEWS_SENTIMENT",
        "topics": "energy",
        "time_from": time_from,
        "time_to": time_to,
        "limit": 1000,
        "sort": "LATEST",
        "apikey": API_KEY,
    }

    try:
        r = requests.get(BASE_URL, params=params, timeout=30)
        r.raise_for_status()
        data = r.json()

        # Alpha Vantage often returns a "Note" when rate limited
        if "Note" in data:
            print(f"Rate limit / API note for {year}-{month:02d}: {data['Note']}")
            return []

        if "Information" in data:
            print(f"API info for {year}-{month:02d}: {data['Information']}")
            return []

        return data.get("feed", [])

    except Exception as e:
        print(f"Error on {year}-{month:02d}: {e}")
        return []

def check_relevance(ticker_list) -> bool:
    if not isinstance(ticker_list, list):
        return False
    found = {item.get("ticker") for item in ticker_list if isinstance(item, dict)}
    return not found.isdisjoint(MY_TICKERS)

if not API_KEY:
    raise ValueError("Missing ALPHAVANTAGE_API_KEY environment variable")

current_year = datetime.now().year
current_month = datetime.now().month

# Example: harvest 2024 through current year
years_to_harvest = [2022,2023]

all_data = []

print(f"Starting harvest for years: {years_to_harvest}")

for year in years_to_harvest:
    for month in range(1, 13):
        if year == current_year and month > current_month:
            continue

        print(f"Pulling {year}-{month:02d}...")
        batch = harvest_chunk(year, month)
        all_data.extend(batch)

        print(f"Collected {len(batch)} articles. Waiting 15s...")
        time.sleep(15)

df_raw = pd.DataFrame(all_data)

if df_raw.empty:
    print("No data found. Check API key, rate limits, or query filters.")
else:
    if "ticker_sentiment" not in df_raw.columns:
        raise KeyError("ticker_sentiment column missing from API response")

    print("Filtering for relevant tickers...")
    df_raw["is_relevant"] = df_raw["ticker_sentiment"].apply(check_relevance)
    master_df = df_raw[df_raw["is_relevant"]].copy()

    if "url" in master_df.columns:
        master_df = master_df.drop_duplicates(subset=["url"])

    if "time_published" in master_df.columns:
        master_df["dt"] = pd.to_datetime(
            master_df["time_published"],
            format="%Y%m%dT%H%M%S",
            errors="coerce"
        )
        master_df = master_df.sort_values("dt", ascending=False)

    filename = f"Energy_BigData_2022_2023.csv"
    master_df.to_csv(filename, index=False)

    print("\nHARVEST COMPLETE")
    print(f"Total raw articles: {len(df_raw)}")
    print(f"Total relevant articles: {len(master_df)}")
    print(f"Saved to: {filename}")

Starting harvest for years: [2024, 2025]
Pulling 2024-01...
Collected 1000 articles. Waiting 15s...
Pulling 2024-02...
Collected 1000 articles. Waiting 15s...
Pulling 2024-03...
Collected 1000 articles. Waiting 15s...
Pulling 2024-04...
Collected 1000 articles. Waiting 15s...
Pulling 2024-05...
Collected 1000 articles. Waiting 15s...
Pulling 2024-06...
Collected 1000 articles. Waiting 15s...
Pulling 2024-07...
Collected 1000 articles. Waiting 15s...
Pulling 2024-08...
Collected 1000 articles. Waiting 15s...
Pulling 2024-09...
Collected 1000 articles. Waiting 15s...
Pulling 2024-10...
Collected 1000 articles. Waiting 15s...
Pulling 2024-11...
Collected 1000 articles. Waiting 15s...
Pulling 2024-12...
Collected 1000 articles. Waiting 15s...
Pulling 2025-01...
Collected 1000 articles. Waiting 15s...
Pulling 2025-02...
Collected 1000 articles. Waiting 15s...
Pulling 2025-03...
Collected 1000 articles. Waiting 15s...
Pulling 2025-04...
Collected 1000 articles. Waiting 15s...
Pulling 2025-05...
Collected 1000 articles. Waiting 15s...
Pulling 2025-06...
Collected 1000 articles. Waiting 15s...
Pulling 2025-07...
Collected 1000 articles. Waiting 15s...
Pulling 2025-08...
Collected 1000 articles. Waiting 15s...
Pulling 2025-09...
Collected 1000 articles. Waiting 15s...
Pulling 2025-10...
Collected 1000 articles. Waiting 15s...
Pulling 2025-11...
API info for 2025-11: We have detected your API key as UZ5WCK1AHB9STKNR and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits.
Collected 0 articles. Waiting 15s...
Pulling 2025-12...
API info for 2025-12: We have detected your API key as UZ5WCK1AHB9STKNR and our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits.
Collected 0 articles. Waiting 15s...
Filtering for relevant tickers...

HARVEST COMPLETE
Total raw articles: 22000
Total relevant articles: 344
Saved to: Energy_BigData_2024_2025.csv

In [ ]:
import pandas as pd
df=pd.read_csv("Energy_BigData_2022_2023.csv")

In [2]:
df.head()

,title,url,time_published,authors,summary,banner_image,source,category_within_source,source_domain,topics,overall_sentiment_score,overall_sentiment_label,ticker_sentiment,is_relevant,dt
0,ExxonMobil announces third-quarter 2025 results,https://corporate.exxonmobil.com/news/news-rel...,20251031T185433,[],Exxon Mobil Corporation announced strong third...,NaN,Exxon Mobil Corporation | ExxonMobil,General,Exxon Mobil Corporation | ExxonMobil,"[{'topic': 'earnings', 'relevance_score': '1.0...",0.417328,Bullish,"[{'ticker': 'XOM', 'relevance_score': '1.00000...",True,2025-10-31 18:54:33
1,Palmetto Grain Brokerage -,https://www.palmettograin.com/news/story/35827...,20251031T180110,['Neha Panjwani'],This article from Barchart discusses whether W...,https://media.barchart.com/contributors-admin/...,Palmetto Grain Brokerage,General,Palmetto Grain Brokerage,"[{'topic': 'financial_markets', 'relevance_sco...",-0.028607,Neutral,"[{'ticker': 'DVN', 'relevance_score': '0.93333...",True,2025-10-31 18:01:10
2,EQT Corp. stock outperforms competitors on str...,https://www.marketwatch.com/data-news/eqt-corp...,20251031T165400,['MarketWatch Automation'],EQT Corp. (EQT) saw its stock advance by 2.15%...,NaN,MarketWatch,General,MarketWatch,"[{'topic': 'financial_markets', 'relevance_sco...",0.413139,Bullish,"[{'ticker': 'EQT', 'relevance_score': '1.00000...",True,2025-10-31 16:54:00
3,EQT Corp. stock outperforms competitors on str...,https://www.marketwatch.com/data-news/eqt-corp...,20251031T165400,['MarketWatch Automation'],"EQT Corp. stock saw a gain of 2.15% on Friday,...",NaN,MarketWatch,General,MarketWatch,"[{'topic': 'financial_markets', 'relevance_sco...",0.461938,Bullish,"[{'ticker': 'EQT', 'relevance_score': '1.00000...",True,2025-10-31 16:54:00
4,EQT Corp. stock outperforms competitors on str...,https://www.marketwatch.com/data-news/eqt-corp...,20251031T165400,['MarketWatch Automation'],EQT Corp. (EQT) stock advanced 2.15% to $53.58...,NaN,MarketWatch,General,MarketWatch,"[{'topic': 'financial_markets', 'relevance_sco...",0.517154,Bullish,"[{'ticker': 'EQT', 'relevance_score': '1.00000...",True,2025-10-31 16:54:00

In [3]:
import ast
import pandas as pd

SC_MAP = {
    # Upstream
    "CL=F": ("crude oil", "Upstream"),
    "USO": ("crude oil", "Upstream"),
    "XOM": ("crude oil", "Upstream"),
    "CVX": ("crude oil", "Upstream"),
    "COP": ("crude oil", "Upstream"),
    "EOG": ("crude oil", "Upstream"),
    "OXY": ("crude oil", "Upstream"),
    "BP": ("crude oil", "Integrated"),
    "SHEL": ("crude oil", "Integrated"),

    # LNG / natural gas
    "EQT": ("LNG", "Upstream"),
    "RRC": ("LNG", "Upstream"),
    "LNG": ("LNG", "Midstream"),
    "TELL": ("LNG", "Midstream"),
    "UNG": ("LNG", "Midstream"),
    "NG=F": ("LNG", "Midstream"),

    # Downstream / refined products
    "VLO": ("diesel", "Downstream"),
    "MPC": ("diesel", "Downstream"),
    "PSX": ("diesel", "Downstream"),
    "HO=F": ("diesel", "Downstream"),
    "CRAK": ("diesel", "Downstream"),
}


def safe_parse(val):
    if pd.isna(val):
        return []
    if isinstance(val, list):
        return val
    if isinstance(val, str):
        try:
            parsed = ast.literal_eval(val)
            return parsed if isinstance(parsed, list) else []
        except (ValueError, SyntaxError):
            return []
    return []


def extract_commodities(ticker_sentiment, sc_map=SC_MAP):
    ticker_list = safe_parse(ticker_sentiment)
    commodities = []

    for item in ticker_list:
        if isinstance(item, dict):
            ticker = item.get("ticker")
            if ticker in sc_map:
                commodity = sc_map[ticker][0]
                if commodity not in commodities:
                    commodities.append(commodity)

    return ",".join(commodities) if commodities else None


def parse_energy_to_merged_format(df_energy):
    df = df_energy.copy()

    df["commodity"] = df["ticker_sentiment"].apply(extract_commodities)
    df["date"] = pd.to_datetime(df["dt"], errors="coerce").dt.strftime("%Y-%m-%d")
    df["description"] = df["summary"]

    result = df[["date", "title", "description", "commodity"]].copy()

    result = result.dropna(subset=["date", "title", "description"])
    result = result.reset_index(drop=True)

    return result
df_parsed = parse_energy_to_merged_format(df)

In [8]:
import pandas as pd

# Load original merged_df if needed
merged_df = pd.read_csv("merged_df.csv")

merged_base = merged_df[["date", "title", "description", "commodity"]].copy()
parsed_base = df_parsed[["date", "title", "description", "commodity"]].copy()
final_df = pd.concat([merged_base, parsed_base], ignore_index=True)
final_df = final_df.drop_duplicates(subset=["date", "title", "description", "commodity"])
final_df["date"] = pd.to_datetime(final_df["date"], errors="coerce")
final_df = final_df.sort_values("date").reset_index(drop=True)
final_df["date"] = final_df["date"].dt.strftime("%Y-%m-%d")
final_df.head()

,date,title,description,commodity
0,2022-01-01,Some Of The Biggest Lies Being Spread About Th...,The events from last Jan. 6 in Washington unfo...,NaN
1,2022-01-01,Austrian Holocaust Survivor 'Mrs. Gertrude' Di...,Gertrude Pressburger became famous during Aust...,NaN
2,2022-01-01,Rep. Alexandria Ocasio-Cortez Rips 'Creepy Wei...,The congresswoman fired back at Republican Ste...,NaN
3,2022-01-02,Chilling Trump Letter Calling For 'Seizure' Of...,The letter was created a day before Trump disc...,NaN
4,2022-01-02,Marjorie Taylor Greene's Personal Twitter Acco...,The Georgia Republican was given the boot afte...,NaN

In [12]:
final_df=final_df[final_df["commodity"].notna() & (final_df["commodity"] != "")]

In [14]:
final_df['date'] = pd.to_datetime(final_df['date'], errors='coerce')
print(final_df['date'].min(), final_df['date'].max())
final_df['year'] = final_df['date'].dt.year
final_df['month'] = final_df['date'].dt.month
final_df['year_month'] = final_df['date'].dt.to_period('M').astype(str)
print(sorted(final_df['year_month'].dropna().unique()))

2022-01-03 00:00:00 2026-03-31 00:00:00
['2022-01', '2022-02', '2022-03', '2022-04', '2022-05', '2022-06', '2022-07', '2022-08', '2022-09', '2022-10', '2022-11', '2022-12', '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', '2025-01', '2025-02', '2025-03', '2025-04', '2025-05', '2025-06', '2025-07', '2025-08', '2025-09', '2025-10', '2026-03']

Labelling

Using LLMs to label domain and extract risk keywords

In [15]:
import json
import time
import pandas as pd

SYSTEM_INSTRUCTION_EXPAND = """
You are an expert Energy Market & Supply Chain Analyst. 
Your task is to analyze news title and description to categorize energy news for a high-precision Risk Management RAG system.

Assign each item:
1. news_category
2. risk_category
3. risk_severity
4. market_sentiment

--- PREDEFINED NEWS CATEGORIES ---
1. Geopolitics & policy
2. Supply (production / upstream)
3. Refining (downstream)
4. Inventory & storage
5. Demand / macro activity
6. LNG & natural gas
7. Weather
8. Shipping & logistics
9. Financial flows / positioning
10. Currency & interest rates
11. Accidents / disruptions
12. Energy transition / structural

--- PREDEFINED RISK CATEGORIES ---
- Supply Chain Blockage
- Production Shortfall
- Refining Outage
- Geopolitical Conflict
- Macro-Economic Cooling
- Inventory Shock
- Infrastructure Damage
- Weather Extremity
- Regulatory Constraint
- No Significant Risk

--- PREDEFINED RISK SEVERITY ---
- Low
- Medium
- High

--- PREDEFINED MARKET SENTIMENT ---
- Bullish
- Bearish
- Neutral

Rules:
- Choose exactly one news_category from the predefined list.
- Choose exactly one risk_category from the predefined list.
- Choose exactly one risk_severity from: Low, Medium, High.
- Choose exactly one market_sentiment from: Bullish, Bearish, Neutral.
- Base the label on the title + description only.
- If the article is mainly about company earnings, stock movement, analyst ratings, or financing, prefer:
  news_category = Financial flows / positioning
- If the article is mainly about LNG, gas supply, pipelines, or gas exports/imports, prefer:
  news_category = LNG & natural gas
- If no material risk is present, use:
  risk_category = No Significant Risk
  risk_severity = Low
- market_sentiment should reflect likely commodity-market impact, not just company-level stock tone.

--- OUTPUT FORMAT ---
Return a JSON list.
Each object must contain exactly:
{
  "id": <input id>,
  "news_category": "<one predefined news category>",
  "risk_category": "<one predefined risk category>",
  "risk_severity": "<Low|Medium|High>",
  "market_sentiment": "<Bullish|Bearish|Neutral>"
}
"""

In [16]:
def build_batch_prompt(batch_df):
    prompt_input = ""
    for idx, row in batch_df.iterrows():
        title = str(row.get("title", "")).strip()
        description = str(row.get("description", "")).strip()
        commodities = str(row.get("relevant_commodities", "")).strip()

        prompt_input += (
            f"ID: {idx} | "
            f"Title: {title} | "
            f"Description: {description} | "
            f"Relevant Commodities: {commodities}\n"
        )

    return SYSTEM_INSTRUCTION_EXPAND + "\n\nAnalyze these items:\n" + prompt_input

In [17]:
def expand_categories_with_llm(
    df,
    client,
    model="gpt-4o-mini",
    batch_size=20,
    sleep_seconds=0.5
):
    working_df = df.copy()

    if "commodity" in working_df.columns:
        working_df = working_df.rename(columns={"commodity": "relevant_commodities"})

    required_cols = ["date", "title", "description", "relevant_commodities"]
    missing = [c for c in required_cols if c not in working_df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    all_results = []

    for start in range(0, len(working_df), batch_size):
        batch = working_df.iloc[start:start + batch_size]
        prompt = build_batch_prompt(batch)

        response = client.responses.create(
            model=model,
            input=prompt,
        )

        text = response.output_text.strip()
        text = text.replace("```json", "").replace("```", "").strip()

        try:
            batch_results = json.loads(text)
        except json.JSONDecodeError as e:
            print(f"JSON parse error for batch starting at row {start}: {e}")
            print(text[:1000])
            continue

        all_results.extend(batch_results)
        print(f"Processed rows {start} to {start + len(batch) - 1}")
        time.sleep(sleep_seconds)

    labels_df = pd.DataFrame(all_results)

    if labels_df.empty:
        raise ValueError("No labels returned from LLM.")

    if "id" not in labels_df.columns:
        raise ValueError("LLM output must contain 'id'.")

    labels_df["id"] = labels_df["id"].astype(int)

    merged = (
        working_df.reset_index()
        .merge(labels_df, left_on="index", right_on="id", how="left")
        .drop(columns=["index", "id"])
    )

    final_cols = [
        "date",
        "title",
        "description",
        "relevant_commodities",
        "news_category",
        "risk_category",
        "risk_severity",
        "market_sentiment",
    ]

    return merged[final_cols]

In [ ]:
# pip install openai

Collecting openai
  Downloading openai-2.30.0-py3-none-any.whl (1.1 MB)
     ---------------------------------------- 1.1/1.1 MB 14.6 MB/s eta 0:00:00
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from openai) (4.13.0)
Collecting distro<2,>=1.7.0
  Downloading distro-1.9.0-py3-none-any.whl (20 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from openai) (0.28.1)
Collecting jiter<1,>=0.10.0
  Downloading jiter-0.13.0-cp311-cp311-win_amd64.whl (204 kB)
     ---------------------------------------- 204.6/204.6 kB ? eta 0:00:00
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from openai) (2.12.5)
Collecting sniffio
  Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Requirement already satisfied: tqdm>4 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in c:\users\calmen\appdata\roaming\python\python311\site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from httpx<1,>=0.23.0->openai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\calmen\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: colorama in c:\users\calmen\appdata\roaming\python\python311\site-packages (from tqdm>4->openai) (0.4.6)
Installing collected packages: sniffio, jiter, distro, openai
Successfully installed distro-1.9.0 jiter-0.13.0 openai-2.30.0 sniffio-1.3.1
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script distro.exe is installed in 'c:\Users\Calmen\AppData\Local\Programs\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script openai.exe is installed in 'c:\Users\Calmen\AppData\Local\Programs\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip available: 22.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from openai import OpenAI
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=OPENAI_API_KEY)

expanded_df = expand_categories_with_llm(
    df=final_df,
    client=client,
    model="gpt-4o-mini",
    batch_size=20
)

expanded_df.head()

Processed rows 0 to 19
Processed rows 20 to 39
Processed rows 40 to 59
Processed rows 60 to 79
Processed rows 80 to 99
Processed rows 100 to 119
Processed rows 120 to 139
Processed rows 140 to 159
Processed rows 160 to 179
Processed rows 180 to 199
Processed rows 200 to 219
Processed rows 220 to 239
Processed rows 240 to 259
Processed rows 260 to 279
Processed rows 280 to 299
Processed rows 300 to 319
Processed rows 320 to 339
Processed rows 340 to 359
Processed rows 360 to 379
Processed rows 380 to 399
Processed rows 400 to 419
Processed rows 420 to 439
Processed rows 440 to 459
Processed rows 460 to 479
Processed rows 480 to 483

,date,title,description,relevant_commodities,news_category,risk_category,risk_severity,market_sentiment
0,2022-01-03,"After Maharashtra, distributors might boycott ...",FMCG product distributors are planning to boyc...,crude oil,Supply (production / upstream),No Significant Risk,Low,Neutral
1,2022-01-03,Colgate items to go off shelves in Maharashtra,FMCG distributors in Maharashtra have announce...,crude oil,Supply (production / upstream),No Significant Risk,Low,Neutral
2,2022-01-04,Colgate in talks with India sales agents after...,Colgate-Palmolive India is in talks with its s...,crude oil,Supply (production / upstream),No Significant Risk,Low,Neutral
3,2022-01-04,Colgate in talks with India sales agents after...,Colgate-Palmolive India is in discussions with...,crude oil,Supply (production / upstream),No Significant Risk,Low,Neutral
4,2022-01-04,US becomes world’s top LNG exporter for first ...,The United States became the world's top expor...,LNG,LNG & natural gas,No Significant Risk,Low,Bullish

In [25]:
def show_counts_only(df):
    cols = ["news_category", "risk_category", "risk_severity", "market_sentiment"]

    for col in cols:
        print(f"\n=== {col} ===")
        print(df[col].fillna("Missing").value_counts())

    print("\n=== relevant_commodities ===")
    commodity_counts = (
        df["relevant_commodities"]
        .fillna("Missing")
        .astype(str)
        .str.split(",")
        .explode()
        .str.strip()
        .value_counts()
    )
    print(commodity_counts)
show_counts_only(expanded_df)

=== news_category ===
news_category
Financial flows / positioning     150
LNG & natural gas                  98
Geopolitics & policy               81
Supply (production / upstream)     71
Energy transition / structural     28
Refining (downstream)              24
Demand / macro activity            17
Accidents / disruptions             5
Shipping & logistics                4
No Significant Risk                 2
Inventory & storage                 2
Weather                             1
Missing                             1
Name: count, dtype: int64

=== risk_category ===
risk_category
No Significant Risk               335
Geopolitical Conflict              41
Production Shortfall               33
Regulatory Constraint              24
Supply Chain Blockage              18
Infrastructure Damage              12
Refining Outage                     6
Macro-Economic Cooling              5
Inventory Shock                     4
Supply (production / upstream)      2
Demand / macro activity             2
Weather Extremity                   1
Missing                             1
Name: count, dtype: int64

=== risk_severity ===
risk_severity
Low        335
Medium      91
High        57
Missing      1
Name: count, dtype: int64

=== market_sentiment ===
market_sentiment
Neutral    200
Bullish    155
Bearish    128
Missing      1
Name: count, dtype: int64

=== relevant_commodities ===
relevant_commodities
crude oil    350
LNG          104
diesel        67
Name: count, dtype: int64

In [26]:
expanded_df.to_csv("final_expanded_df.csv", index=False)